# Generated by Django 5.0 on 2024-01-14 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actions', models.CharField(choices=[('Select', 'Select'), ('View', 'View'), ('Edit', 'Edit'), ('Delete', 'Delete')], default='Select', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Role_And_Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('permission', models.ManyToManyField(blank=True, to='auth.permission')),
            ],
        ),
    ]
