# Generated by Django 5.0 on 2024-01-15 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_product',
            name='user',
            field=models.ForeignKey(blank=True, help_text='which is uploading product for selling', null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.registration_all'),
        ),
        migrations.AddField(
            model_name='image_upload',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.add_product'),
        ),
    ]
